### ISSUE TITLE
/trlist does't work

### ISSUE THREAD

**Issue by pvolkov** [meinside/telegram-bot-transmission#1]
@meinside When i type or select /trlist command, i can't see my download list.
/logs say this:
2016-08-27 08:52:26 err: Bad Request: Can't parse message text: Can't find end of the entity starting at byte offset 280

**Comment by meinside** [comment]
What torrents do you have in the list?
That message seems to be from Telegram server, which complains about mismatching markups.
Check if your torrents' names have '_' or '*' in them.
If they do, it would be helpful if you let me know the names.

**Comment by pvolkov** [comment]
Here is my torrent list. "The Legend of Tarzan_2016_Toriyal_Rutracker.avi" have "_" in name. I deleted it and /trlist just worked. Funny bug in Telegram =)
<img width="454" alt="2016-08-29 6 48 35" src="https://cloud.githubusercontent.com/assets/457569/18040285/a99d2868-6db4-11e6-9f15-df43f2efb403.png">

**Comment by meinside** [comment]
Could you please check again with the latest revision ec14a59e0733c71067e4aaea99391975d71ef524?

It now replaces those problematic markdown characters from torrent names, so if it was fixed correctly, you would have no problem with such file names :-)

**Comment by pvolkov** [comment]
Yeap! All done! =) Bug is fixed!
